# Generated by Django 3.2.9 on 2022-01-16 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('post_number', models.IntegerField()),
                ('note', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BankNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('bank_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('vat_number', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='client.address')),
                ('bank_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='client.banknumber')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='client.person')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('duration', models.IntegerField()),
                ('start_task', models.TimeField()),
                ('end_task', models.TimeField()),
                ('task_reward', models.FloatField()),
                ('other_expense_amount', models.FloatField()),
                ('other_expense_note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.CharField(max_length=255)),
                ('reward', models.IntegerField()),
                ('total_expense', models.FloatField()),
                ('prepaid_expense', models.FloatField()),
                ('debt', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheet', to='client.profile')),
                ('work_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet', to='client.worktask')),
            ],
        ),
    ]
