# Generated by Django 4.0.8 on 2022-10-04 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone number')),
                ('id_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='id number')),
                ('vat_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='vat number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='debt')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='client.client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccounts', to='client.client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='payments',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='client.client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='person',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='client.client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worksheets', to='client.client', verbose_name='client'),
        ),
    ]
