# Generated by Django 4.0.8 on 2022-10-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_remove_address_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ID number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='vat_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='VAT number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
