# Generated by Django 3.2.9 on 2022-02-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20220116_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='work_task',
        ),
        migrations.AddField(
            model_name='worktask',
            name='worksheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='worktask', to='client.worksheet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='debt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='prepaid_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='client.profile'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='total_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='end_task',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='other_expense_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='other_expense_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='start_task',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worktask',
            name='task_reward',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
