# Generated by Django 3.2.9 on 2022-04-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20220221_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='total_other_task_expense',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='total_reward',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_id',
            field=models.CharField(max_length=4),
        ),
    ]
