# Generated by Django 4.0.8 on 2022-10-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_address_note_alter_client_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='address',
            name='post_number',
            field=models.CharField(max_length=5, verbose_name='post_number'),
        ),
    ]
