# Generated by Django 4.0.8 on 2022-10-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_person_email_alter_address_post_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='phone number'),
        ),
    ]
