# Generated by Django 3.2.9 on 2022-04-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20220418_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prepaid_expense',
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateField(),
        ),
    ]
